### ISSUE TITLE
Incorrect PD API call?

### ISSUE THREAD

**Issue by zleswomp** [hubot-scripts/hubot-pager-me#100]
When I run `pager my schedule` I get a stacktrace that looks like the following:

```
[Mon Oct 17 2016 13:00:05 GMT-0700 (PDT)] ERROR Error: 404 back from /schedules/AAAAAAA/entries
  at PagerDutyError.Error (native)
  at new PagerDutyError (/Users/zach/hubot/node_modules/hubot-pager-me/src/pagerduty.coffee:10:1, <js>:26:51)
  at /Users/zach/hubot/node_modules/hubot-pager-me/src/pagerduty.coffee:44:20, <js>:74:16
  at IncomingMessage.<anonymous> (/Users/zach/hubot/node_modules/scoped-http-client/src/index.js:95:22)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

I'm only guessing, but I think that call should be `/schedules#AAAAAAA/entries`.  If not an incorrect API call, what have I done wrong?

**Comment by stephenyeargin** [comment]
Discovered in #101 that this Hubot plugin requires a V1 key until #98 lands. Closing this off in favor of #98.
