### ISSUE TITLE
Doesn't return on-call schedule

### ISSUE THREAD

**Issue by AnudeepReddyJ21** [hubot-scripts/hubot-pager-me#101]
Hi,

When I command Hubot 'who's on call', I get a 404 back from schedules. The other commands are working fine. I have pasted my error below. 

ERROR Error: 404 back from /schedules/XXXXXXX/entries
  at PagerDutyError.Error (native)
  at new PagerDutyError (/Users/duolingo4/customhubot2/node_modules/hubot-pager-me/src/pagerduty.coffee:10:1, <js>:26:51)
  at /Users/duolingo4/customhubot2/node_modules/hubot-pager-me/src/pagerduty.coffee:44:20, <js>:74:16
  at IncomingMessage.<anonymous> (/Users/duolingo4/customhubot2/node_modules/scoped-http-client/src/index.js:95:22)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:893:12)
  at doNTCallback2 (node.js:429:9)
  at process._tickCallback (node.js:343:17)

Thanks,

Anudeep

**Comment by AnudeepReddyJ21** [comment]
Hi,

Sorry the issue is I created a v2 API key instead of v1. Once I created the v1 key, it worked.

Thanks,

Anudeep
